Added up

diff --git a/commands/up/up b/commands/up/up
--- a/commands/up/up
+++ b/commands/up/up
@@ -1,33 +1,23 @@
 #!/bin/bash
 
-if [ "$EUID" -ne 0 ]; then
-    echo "Please run with sudo"
-    exit 1
-fi
-
-up_function='
-up() {
-    local take_argument=$1
-
-    if ! [[ "$take_argument" =~ ^[0-9]+$ ]]; then
-        echo "Error: Please provide a valid number"
-        return 1
-    fi
-
-    while [[ $take_argument -ne 0 ]]
-    do 
-        if [[ "$(pwd)" == "/" ]]; then
-            break
-        fi
-        cd ..
-        (( take_argument-- ))
-    done
-}
-'
 if ! grep -q "up()" ~/.bashrc; then
-    echo "$up_function" >> ~/.bashrc
+    echo 'up() {' >> ~/.bashrc
+    echo '    local take_argument=$1' >> ~/.bashrc
+    echo '    if ! [[ "$take_argument" =~ ^[0-9]+$ ]]; then' >> ~/.bashrc
+    echo '        echo "Error: Please provide a valid number"' >> ~/.bashrc
+    echo '        return 1' >> ~/.bashrc
+    echo '    fi' >> ~/.bashrc
+    echo '    while [[ $take_argument -ne 0 ]]' >> ~/.bashrc
+    echo '    do' >> ~/.bashrc
+    echo '        if [[ "$(pwd)" == "/" ]]; then' >> ~/.bashrc
+    echo '            break' >> ~/.bashrc
+    echo '        fi' >> ~/.bashrc
+    echo '        cd ..' >> ~/.bashrc
+    echo '        (( take_argument-- ))' >> ~/.bashrc
+    echo '    done' >> ~/.bashrc
+    echo '}' >> ~/.bashrc
     source ~/.bashrc
     echo "Now you can go up! Until /"
 else
-    echo "You're already going up!"
+    echo "You are already going up!"
 fi
